# Generated by Django 5.2.3 on 2025-06-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestion',
            new_name='Contact',
        ),
    ]
